const countries = [
    { inicials: "AFG", nameEN: "Afghanistan", nameBR: "Afeganistão", code: "AF" },
    { inicials: "AGO", nameEN: "Angola", nameBR: "Angola", code: "AO" },
    { inicials: "ALB", nameEN: "Albania", nameBR: "Albânia", code: "AL" },
    { inicials: "AND", nameEN: "Andorra", nameBR: "Andorra", code: "AN" },
    {
        inicials: "ARE",
        nameEN: "United Arab Emirates",
        nameBR: "Emirados Árabes Unidos",
        code: "AE",
    },
    { inicials: "ARG", nameEN: "Argentina", nameBR: "Argentina", code: "AR" },
    { inicials: "ARM", nameEN: "Armenia", nameBR: "Armênia", code: "AM" },
    { inicials: "ATG", nameEN: "Antigua and Barbuda", nameBR: "Antígua e Barbuda", code: "AG" },
    { inicials: "AUS", nameEN: "Australia", nameBR: "Austrália", code: "AU" },
    { inicials: "AUT", nameEN: "Austria", nameBR: "Áustria", code: "AT" },
    { inicials: "AZE", nameEN: "Azerbaijan", nameBR: "Azerbaijão", code: "AZ" },
    { inicials: "BDI", nameEN: "Burundi", nameBR: "Burundi", code: "BI" },
    { inicials: "BEL", nameEN: "Belgium", nameBR: "Bélgica", code: "BE" },
    { inicials: "BEN", nameEN: "Benin", nameBR: "Benim", code: "BJ" },
    { inicials: "BFA", nameEN: "Burkina Faso", nameBR: "Burkina Faso", code: "BF" },
    { inicials: "BGD", nameEN: "Bangladesh", nameBR: "Bangladesh", code: "BD" },
    { inicials: "BGR", nameEN: "Bulgaria", nameBR: "Bulgária", code: "BG" },
    { inicials: "BHR", nameEN: "Bahrain", nameBR: "Bahrein", code: "BH" },
    { inicials: "BHS", nameEN: "Bahamas", nameBR: "Bahamas", code: "BS" },
    {
        inicials: "BIH",
        nameEN: "Bosnia and Herzegovina",
        nameBR: "Bósnia e Herzegovina",
        code: "BA",
    },
    { inicials: "BLR", nameEN: "Belarus", nameBR: "Bielorrússia", code: "BY" },
    { inicials: "BLZ", nameEN: "Belize", nameBR: "Belize", code: "BZ" },
    { inicials: "BOL", nameEN: "Bolivia", nameBR: "Bolívia", code: "BO" },
    { inicials: "BRA", nameEN: "Brazil", nameBR: "Brasil", code: "BR" },
    { inicials: "BRB", nameEN: "Barbados", nameBR: "Barbados", code: "BB" },
    { inicials: "BRN", nameEN: "Brunei", nameBR: "Brunei", code: "BN" },
    { inicials: "BTN", nameEN: "Bhutan", nameBR: "Butão", code: "BT" },
    { inicials: "BWA", nameEN: "Botswana", nameBR: "Botsuana", code: "BW" },
    {
        inicials: "CAF",
        nameEN: "Central African Republic",
        nameBR: "República Centro-Africana",
        code: "CF",
    },
    { inicials: "CAN", nameEN: "Canada", nameBR: "Canadá", code: "CA" },
    { inicials: "CHE", nameEN: "Switzerland", nameBR: "Suíça", code: "CH" },
    { inicials: "CHL", nameEN: "Chile", nameBR: "Chile", code: "CL" },
    { inicials: "CHN", nameEN: "China", nameBR: "China", code: "CN" },
    { inicials: "CIV", nameEN: "Ivory Coast", nameBR: "Costa do Marfim", code: "CI" },
    { inicials: "CMR", nameEN: "Cameroon", nameBR: "Camarões", code: "CM" },
    {
        inicials: "COD",
        nameEN: "Democratic Republic of the Congo",
        nameBR: "República Democrática do Congo",
        code: "CD",
    },
    { inicials: "COG", nameEN: "Republic of the Congo", nameBR: "República do Congo", code: "CG" },
    { inicials: "COL", nameEN: "Colombia", nameBR: "Colômbia", code: "CO" },
    { inicials: "COM", nameEN: "Comoros", nameBR: "Comores", code: "KM" },
    { inicials: "CPV", nameEN: "Cape Verde", nameBR: "Cabo Verde", code: "CV" },
    { inicials: "CRI", nameEN: "Costa Rica", nameBR: "Costa Rica", code: "CR" },
    { inicials: "CUB", nameEN: "Cuba", nameBR: "Cuba", code: "CU" },
    { inicials: "CYP", nameEN: "Cyprus", nameBR: "Chipre", code: "CY" },
    { inicials: "CZE", nameEN: "Czech Republic", nameBR: "República Checa", code: "CZ" },
    { inicials: "DEU", nameEN: "Germany", nameBR: "Alemanha", code: "DE" },
    { inicials: "DJI", nameEN: "Djibouti", nameBR: "Djibuti", code: "DJ" },
    { inicials: "DMA", nameEN: "Dominica", nameBR: "Dominica", code: "DM" },
    { inicials: "DNK", nameEN: "Denmark", nameBR: "Dinamarca", code: "DK" },
    { inicials: "DOM", nameEN: "Dominican Republic", nameBR: "República Dominicana", code: "DO" },
    { inicials: "DZA", nameEN: "Algeria", nameBR: "Argélia", code: "DZ" },
    { inicials: "ECU", nameEN: "Ecuador", nameBR: "Equador", code: "EC" },
    { inicials: "EGY", nameEN: "Egypt", nameBR: "Egito", code: "EG" },
    { inicials: "ERI", nameEN: "Eritrea", nameBR: "Eritreia", code: "ER" },
    { inicials: "ESH", nameEN: "Western Sahara", nameBR: "Saara Ocidental", code: "EH" },
    { inicials: "ESP", nameEN: "Spain", nameBR: "Espanha", code: "ES" },
    { inicials: "EST", nameEN: "Estonia", nameBR: "Estônia", code: "EE" },
    { inicials: "ETH", nameEN: "Ethiopia", nameBR: "Etiópia", code: "ET" },
    { inicials: "FIN", nameEN: "Finland", nameBR: "Finlândia", code: "FI" },
    { inicials: "FJI", nameEN: "Fiji", nameBR: "Fiji", code: "FJ" },
    { inicials: "FRA", nameEN: "France", nameBR: "França", code: "FR" },
    { inicials: "FSM", nameEN: "Micronesia", nameBR: "Micronésia", code: "FM" },
    { inicials: "GAB", nameEN: "Gabon", nameBR: "Gabão", code: "GA" },
    { inicials: "GBR", nameEN: "United Kingdom", nameBR: "Reino Unido", code: "GB" },
    { inicials: "GEO", nameEN: "Georgia", nameBR: "Geórgia", code: "GE" },
    { inicials: "GHA", nameEN: "Ghana", nameBR: "Gana", code: "GH" },
    { inicials: "GIN", nameEN: "Guinea", nameBR: "Guiné", code: "GN" },
    { inicials: "GMB", nameEN: "Gambia", nameBR: "Gâmbia", code: "GM" },
    { inicials: "GNB", nameEN: "Guinea-Bissau", nameBR: "Guiné-Bissau", code: "GW" },
    { inicials: "GNQ", nameEN: "Equatorial Guinea", nameBR: "Guiné Equatorial", code: "GQ" },
    { inicials: "GRC", nameEN: "Greece", nameBR: "Grécia", code: "GR" },
    { inicials: "GRD", nameEN: "Grenada", nameBR: "Granada", code: "GD" },
    { inicials: "GTM", nameEN: "Guatemala", nameBR: "Guatemala", code: "GT" },
    { inicials: "GUY", nameEN: "Guyana", nameBR: "Guiana", code: "GY" },
    { inicials: "HND", nameEN: "Honduras", nameBR: "Honduras", code: "HN" },
    { inicials: "HRV", nameEN: "Croatia", nameBR: "Croácia", code: "HR" },
    { inicials: "HTI", nameEN: "Haiti", nameBR: "Haiti", code: "HT" },
    { inicials: "HUN", nameEN: "Hungary", nameBR: "Hungria", code: "HU" },
    { inicials: "IDN", nameEN: "Indonesia", nameBR: "Indonésia", code: "ID" },
    { inicials: "IND", nameEN: "India", nameBR: "Índia", code: "IN" },
    { inicials: "IRL", nameEN: "Ireland", nameBR: "Irlanda", code: "IE" },
    { inicials: "IRN", nameEN: "Iran", nameBR: "Irã", code: "IR" },
    { inicials: "IRQ", nameEN: "Iraq", nameBR: "Iraque", code: "IQ" },
    { inicials: "ISL", nameEN: "Iceland", nameBR: "Islândia", code: "IS" },
    { inicials: "ISR", nameEN: "Israel", nameBR: "Israel", code: "IL" },
    { inicials: "ITA", nameEN: "Italy", nameBR: "Itália", code: "IT" },
    { inicials: "JAM", nameEN: "Jamaica", nameBR: "Jamaica", code: "JM" },
    { inicials: "JOR", nameEN: "Jordan", nameBR: "Jordânia", code: "JO" },
    { inicials: "JPN", nameEN: "Japan", nameBR: "Japão", code: "JP" },
    { inicials: "KAZ", nameEN: "Kazakhstan", nameBR: "Cazaquistão", code: "KZ" },
    { inicials: "KEN", nameEN: "Kenya", nameBR: "Quênia", code: "KE" },
    { inicials: "KGZ", nameEN: "Kyrgyzstan", nameBR: "Quirguistão", code: "KG" },
    { inicials: "KHM", nameEN: "Cambodia", nameBR: "Camboja", code: "KH" },
    { inicials: "KIR", nameEN: "Kiribati", nameBR: "Kiribati", code: "KI" },
    {
        inicials: "KNA",
        nameEN: "Saint Kitts and Nevis",
        nameBR: "São Cristóvão e Nevis",
        code: "KN",
    },
    { inicials: "KOR", nameEN: "South Korea", nameBR: "Coreia do Sul", code: "KR" },
    { inicials: "KWT", nameEN: "Kuwait", nameBR: "Kuwait", code: "KW" },
    { inicials: "LAO", nameEN: "Laos", nameBR: "Laos", code: "LA" },
    { inicials: "LBN", nameEN: "Lebanon", nameBR: "Líbano", code: "LB" },
    { inicials: "LBR", nameEN: "Liberia", nameBR: "Libéria", code: "LR" },
    { inicials: "LBY", nameEN: "Libya", nameBR: "Líbia", code: "LY" },
    { inicials: "LCA", nameEN: "Saint Lucia", nameBR: "Santa Lúcia", code: "LC" },
    { inicials: "LIE", nameEN: "Liechtenstein", nameBR: "Liechtenstein", code: "LI" },
    { inicials: "LKA", nameEN: "Sri Lanka", nameBR: "Sri Lanka", code: "LK" },
    { inicials: "LSO", nameEN: "Lesotho", nameBR: "Lesoto", code: "LS" },
    { inicials: "LTU", nameEN: "Lithuania", nameBR: "Lituânia", code: "LT" },
    { inicials: "LUX", nameEN: "Luxembourg", nameBR: "Luxemburgo", code: "LU" },
    { inicials: "LVA", nameEN: "Latvia", nameBR: "Letônia", code: "LV" },
    { inicials: "MAR", nameEN: "Morocco", nameBR: "Marrocos", code: "MA" },
    { inicials: "MCO", nameEN: "Monaco", nameBR: "Mônaco", code: "MC" },
    { inicials: "MDA", nameEN: "Moldova", nameBR: "Moldávia", code: "MD" },
    { inicials: "MDG", nameEN: "Madagascar", nameBR: "Madagascar", code: "MG" },
    { inicials: "MDV", nameEN: "Maldives", nameBR: "Maldivas", code: "MV" },
    { inicials: "MEX", nameEN: "Mexico", nameBR: "México", code: "MX" },
    { inicials: "MHL", nameEN: "Marshall Islands", nameBR: "Ilhas Marshall", code: "MH" },
    { inicials: "MKD", nameEN: "Macedonia", nameBR: "Macedônia", code: "MK" },
    { inicials: "MLI", nameEN: "Mali", nameBR: "Mali", code: "ML" },
    { inicials: "MLT", nameEN: "Malta", nameBR: "Malta", code: "MT" },
    { inicials: "MMR", nameEN: "Myanmar", nameBR: "Mianmar", code: "MM" },
    { inicials: "MNE", nameEN: "Montenegro", nameBR: "Montenegro", code: "ME" },
    { inicials: "MNG", nameEN: "Mongolia", nameBR: "Mongólia", code: "MN" },
    { inicials: "MOZ", nameEN: "Mozambique", nameBR: "Moçambique", code: "MZ" },
    { inicials: "MRT", nameEN: "Mauritania", nameBR: "Mauritânia", code: "MR" },
    { inicials: "MUS", nameEN: "Mauritius", nameBR: "Maurício", code: "MU" },
    { inicials: "MWI", nameEN: "Malawi", nameBR: "Malauí", code: "MW" },
    { inicials: "MYS", nameEN: "Malaysia", nameBR: "Malásia", code: "MY" },
    { inicials: "NAM", nameEN: "Namibia", nameBR: "Namíbia", code: "NA" },
    { inicials: "NER", nameEN: "Niger", nameBR: "Níger", code: "NE" },
    { inicials: "NGA", nameEN: "Nigeria", nameBR: "Nigéria", code: "NG" },
    { inicials: "NIC", nameEN: "Nicaragua", nameBR: "Nicarágua", code: "NI" },
    { inicials: "NLD", nameEN: "Netherlands", nameBR: "Holanda", code: "NL" },
    { inicials: "NOR", nameEN: "Norway", nameBR: "Noruega", code: "NO" },
    { inicials: "NPL", nameEN: "Nepal", nameBR: "Nepal", code: "NP" },
    { inicials: "NRU", nameEN: "Nauru", nameBR: "Nauru", code: "NR" },
    { inicials: "NZL", nameEN: "New Zealand", nameBR: "Nova Zelândia", code: "NZ" },
    { inicials: "OMN", nameEN: "Oman", nameBR: "Omã", code: "OM" },
    { inicials: "PAK", nameEN: "Pakistan", nameBR: "Paquistão", code: "PK" },
    { inicials: "PAN", nameEN: "Panama", nameBR: "Panamá", code: "PA" },
    { inicials: "PER", nameEN: "Peru", nameBR: "Peru", code: "PE" },
    { inicials: "PHL", nameEN: "Philippines", nameBR: "Filipinas", code: "PH" },
    { inicials: "PLW", nameEN: "Palau", nameBR: "Palau", code: "PW" },
    { inicials: "PNG", nameEN: "Papua New Guinea", nameBR: "Papua Nova Guiné", code: "PG" },
    { inicials: "POL", nameEN: "Poland", nameBR: "Polônia", code: "PL" },
    { inicials: "PRK", nameEN: "North Korea", nameBR: "Coreia do Norte", code: "KP" },
    { inicials: "PRT", nameEN: "Portugal", nameBR: "Portugal", code: "PT" },
    { inicials: "PRY", nameEN: "Paraguay", nameBR: "Paraguai", code: "PY" },
    { inicials: "QAT", nameEN: "Qatar", nameBR: "Catar", code: "QA" },
    { inicials: "ROU", nameEN: "Romania", nameBR: "Romênia", code: "RO" },
    { inicials: "RUS", nameEN: "Russia", nameBR: "Rússia", code: "RU" },
    { inicials: "RWA", nameEN: "Rwanda", nameBR: "Ruanda", code: "RW" },
    { inicials: "SAU", nameEN: "Saudi Arabia", nameBR: "Arábia Saudita", code: "SA" },
    { inicials: "SDN", nameEN: "Sudan", nameBR: "Sudão", code: "SD" },
    { inicials: "SEN", nameEN: "Senegal", nameBR: "Senegal", code: "SN" },
    { inicials: "SGP", nameEN: "Singapore", nameBR: "Cingapura", code: "SG" },
    { inicials: "SLB", nameEN: "Solomon Islands", nameBR: "Ilhas Salomão", code: "SB" },
    { inicials: "SLE", nameEN: "Sierra Leone", nameBR: "Serra Leoa", code: "SL" },
    { inicials: "SLV", nameEN: "El Salvador", nameBR: "El Salvador", code: "SV" },
    { inicials: "SMR", nameEN: "San Marino", nameBR: "São Marino", code: "SM" },
    { inicials: "SOM", nameEN: "Somalia", nameBR: "Somália", code: "SO" },
    { inicials: "SRB", nameEN: "Serbia", nameBR: "Sérvia", code: "RS" },
    { inicials: "STP", nameEN: "São Tomé and Príncipe", nameBR: "São Tomé e Príncipe", code: "ST" },
    { inicials: "SUR", nameEN: "Suriname", nameBR: "Suriname", code: "SR" },
    { inicials: "SVK", nameEN: "Slovakia", nameBR: "Eslováquia", code: "SK" },
    { inicials: "SVN", nameEN: "Slovenia", nameBR: "Eslovênia", code: "SI" },
    { inicials: "SWE", nameEN: "Sweden", nameBR: "Suécia", code: "SE" },
    { inicials: "SWZ", nameEN: "Swaziland", nameBR: "Suazilândia", code: "SZ" },
    { inicials: "SYC", nameEN: "Seychelles", nameBR: "Seicheles", code: "SC" },
    { inicials: "SYR", nameEN: "Syria", nameBR: "Síria", code: "SY" },
    { inicials: "TCD", nameEN: "Chad", nameBR: "Chade", code: "TD" },
    { inicials: "TGO", nameEN: "Togo", nameBR: "Togo", code: "TG" },
    { inicials: "THA", nameEN: "Thailand", nameBR: "Tailândia", code: "TH" },
    { inicials: "TJK", nameEN: "Tajikistan", nameBR: "Tadjiquistão", code: "TJ" },
    { inicials: "TKM", nameEN: "Turkmenistan", nameBR: "Turcomenistão", code: "TM" },
    { inicials: "TLS", nameEN: "East Timor", nameBR: "Timor Leste", code: "TL" },
    { inicials: "TON", nameEN: "Tonga", nameBR: "Tonga", code: "TO" },
    { inicials: "TTO", nameEN: "Trinidad and Tobago", nameBR: "Trindade e Tobago", code: "TT" },
    { inicials: "TUN", nameEN: "Tunisia", nameBR: "Tunísia", code: "TN" },
    { inicials: "TUR", nameEN: "Turkey", nameBR: "Turquia", code: "TR" },
    { inicials: "TUV", nameEN: "Tuvalu", nameBR: "Tuvalu", code: "TV" },
    { inicials: "TWN", nameEN: "Taiwan", nameBR: "Taiwan", code: "TW" },
    { inicials: "TZA", nameEN: "Tanzania", nameBR: "Tanzânia", code: "TZ" },
    { inicials: "UGA", nameEN: "Uganda", nameBR: "Uganda", code: "UG" },
    { inicials: "UKR", nameEN: "Ukraine", nameBR: "Ucrânia", code: "UA" },
    { inicials: "URY", nameEN: "Uruguay", nameBR: "Uruguai", code: "UY" },
    { inicials: "USA", nameEN: "United States", nameBR: "Estados Unidos", code: "US" },
    { inicials: "UZB", nameEN: "Uzbekistan", nameBR: "Uzbequistão", code: "UZ" },
    { inicials: "VAT", nameEN: "Vatican City", nameBR: "Vaticano", code: "VA" },
    {
        inicials: "VCT",
        nameEN: "Saint Vincent and the Grenadines",
        nameBR: "São Vicente e Granadinas",
        code: "VC",
    },
    { inicials: "VEN", nameEN: "Venezuela", nameBR: "Venezuela", code: "VE" },
    { inicials: "VNM", nameEN: "Vietnam", nameBR: "Vietnã", code: "VN" },
    { inicials: "VUT", nameEN: "Vanuatu", nameBR: "Vanuatu", code: "VU" },
    { inicials: "WSM", nameEN: "Samoa", nameBR: "Samoa", code: "WS" },
    { inicials: "YEM", nameEN: "Yemen", nameBR: "Iêmen", code: "YE" },
    { inicials: "ZAF", nameEN: "South Africa", nameBR: "África do Sul", code: "ZA" },
    { inicials: "ZMB", nameEN: "Zambia", nameBR: "Zâmbia", code: "ZM" },
];

export default countries;
