const countries = [
    { initials: 'AFG', name: 'Afghanistan', code: 'AF' },
    // { initials: 'ALB', name: 'Albania', code: 'AL' },
    // { initials: 'DZA', name: 'Algeria', code: 'DZ' },
    // { initials: 'AND', name: 'Andorra', code: 'AD' },
    // { initials: 'AGO', name: 'Angola', code: 'AO' },
    // { initials: 'ATG', name: 'Antigua and Barbuda', code: 'AG' },
    // { initials: 'ARG', name: 'Argentina', code: 'AR' },
    // { initials: 'ARM', name: 'Armenia', code: 'AM' },
    // { initials: 'AUS', name: 'Australia', code: 'AU' },
    // { initials: 'AUT', name: 'Austria', code: 'AT' },
    // { initials: 'AZE', name: 'Azerbaijan', code: 'AZ' },
    // { initials: 'BHS', name: 'Bahamas', code: 'BS' },
    // { initials: 'BHR', name: 'Bahrain', code: 'BH' },
    // { initials: 'BGD', name: 'Bangladesh', code: 'BD' },
    // { initials: 'BRB', name: 'Barbados', code: 'BB' },
    // { initials: 'BLR', name: 'Belarus', code: 'BY' },
    // { initials: 'BEL', name: 'Belgium', code: 'BE' },
    // { initials: 'BLZ', name: 'Belize', code: 'BZ' },
    // { initials: 'BEN', name: 'Benin', code: 'BJ' },
    { initials: 'BTN', name: 'Bhutan', code: 'BT' },
    // { initials: 'BOL', name: 'Bolivia', code: 'BO' },
    // { initials: 'BIH', name: 'Bosnia and Herzegovina', code: 'BA' },
    // { initials: 'BWA', name: 'Botswana', code: 'BW' },
    // { initials: 'BRA', name: 'Brazil', code: 'BR' },
    // { initials: 'BRN', name: 'Brunei', code: 'BN' },
    // { initials: 'BGR', name: 'Bulgaria', code: 'BG' },
    // { initials: 'BFA', name: 'Burkina Faso', code: 'BF' },
    // { initials: 'BDI', name: 'Burundi', code: 'BI' },
    // { initials: 'KHM', name: 'Cambodia', code: 'KH' },
    // { initials: 'CMR', name: 'Cameroon', code: 'CM' },
    // { initials: 'CAN', name: 'Canada', code: 'CA' },
    // { initials: 'CPV', name: 'Cape Verde', code: 'CV' },
    // { initials: 'CAF', name: 'Central African Republic', code: 'CF' },
    // { initials: 'TCD', name: 'Chad', code: 'TD' },
    // { initials: 'CHL', name: 'Chile', code: 'CL' },
    // { initials: 'CHN', name: 'China', code: 'CN' },
    // { initials: 'COL', name: 'Colombia', code: 'CO' },
    // { initials: 'COM', name: 'Comoros', code: 'KM' },
    // { initials: 'CRI', name: 'Costa Rica', code: 'CR' },
    // { initials: 'HRV', name: 'Croatia', code: 'HR' },
    // { initials: 'CUB', name: 'Cuba', code: 'CU' },
    // { initials: 'CYP', name: 'Cyprus', code: 'CY' },
    // { initials: 'CZE', name: 'Czech Republic', code: 'CZ' },
    // { initials: 'COD', name: 'Democratic Republic of the Congo', code: 'CD' },
    // { initials: 'DNK', name: 'Denmark', code: 'DK' },
    // { initials: 'DJI', name: 'Djibouti', code: 'DJ' },
    // { initials: 'DMA', name: 'Dominica', code: 'DM' },
    // { initials: 'DOM', name: 'Dominican Republic', code: 'DO' },
    // { initials: 'TLS', name: 'East Timor', code: 'TL' },
    // { initials: 'ECU', name: 'Ecuador', code: 'EC' },
    // { initials: 'EGY', name: 'Egypt', code: 'EG' },
    // { initials: 'SLV', name: 'El Salvador', code: 'SV' },
    // { initials: 'GNQ', name: 'Equatorial Guinea', code: 'GQ' },
    // { initials: 'ERI', name: 'Eritrea', code: 'ER' },
    // { initials: 'EST', name: 'Estonia', code: 'EE' },
    // { initials: 'ETH', name: 'Ethiopia', code: 'ET' },
    // { initials: 'FJI', name: 'Fiji', code: 'FJ' },
    // { initials: 'FIN', name: 'Finland', code: 'FI' },
    // { initials: 'FRA', name: 'France', code: 'FR' },
    // { initials: 'GAB', name: 'Gabon', code: 'GA' },
    // { initials: 'GMB', name: 'Gambia', code: 'GM' },
    // { initials: 'GEO', name: 'Georgia', code: 'GE' },
    // { initials: 'DEU', name: 'Germany', code: 'DE' },
    // { initials: 'GHA', name: 'Ghana', code: 'GH' },
    // { initials: 'GRC', name: 'Greece', code: 'GR' },
    // { initials: 'GRD', name: 'Grenada', code: 'GD' },
    // { initials: 'GTM', name: 'Guatemala', code: 'GT' },
    // { initials: 'GIN', name: 'Guinea', code: 'GN' },
    // { initials: 'GNB', name: 'Guinea-Bissau', code: 'GW' },
    // { initials: 'GUY', name: 'Guyana', code: 'GY' },
    // { initials: 'HTI', name: 'Haiti', code: 'HT' },
    // { initials: 'HND', name: 'Honduras', code: 'HN' },
    // { initials: 'HUN', name: 'Hungary', code: 'HU' },
    // { initials: 'ISL', name: 'Iceland', code: 'IS' },
    // { initials: 'IND', name: 'India', code: 'IN' },
    // { initials: 'IDN', name: 'Indonesia', code: 'ID' },
    // { initials: 'IRN', name: 'Iran', code: 'IR' },
    // { initials: 'IRQ', name: 'Iraq', code: 'IQ' },
    // { initials: 'IRL', name: 'Ireland', code: 'IE' },
    // { initials: 'ISR', name: 'Israel', code: 'IL' },
    // { initials: 'ITA', name: 'Italy', code: 'IT' },
    // { initials: 'CIV', name: 'Ivory Coast', code: 'CI' },
    // { initials: 'JAM', name: 'Jamaica', code: 'JM' },
    // { initials: 'JPN', name: 'Japan', code: 'JP' },
    // { initials: 'JOR', name: 'Jordan', code: 'JO' },
    // { initials: 'KAZ', name: 'Kazakhstan', code: 'KZ' },
    // { initials: 'KEN', name: 'Kenya', code: 'KE' },
    // { initials: 'KIR', name: 'Kiribati', code: 'KI' },
    // { initials: 'KWT', name: 'Kuwait', code: 'KW' },
    // { initials: 'KGZ', name: 'Kyrgyzstan', code: 'KG' },
    // { initials: 'LAO', name: 'Laos', code: 'LA' },
    // { initials: 'LVA', name: 'Latvia', code: 'LV' },
    // { initials: 'LBN', name: 'Lebanon', code: 'LB' },
    // { initials: 'LSO', name: 'Lesotho', code: 'LS' },
    // { initials: 'LBR', name: 'Liberia', code: 'LR' },
    // { initials: 'LBY', name: 'Libya', code: 'LY' },
    // { initials: 'LIE', name: 'Liechtenstein', code: 'LI' },
    // { initials: 'LTU', name: 'Lithuania', code: 'LT' },
    // { initials: 'LUX', name: 'Luxembourg', code: 'LU' },
    // { initials: 'MKD', name: 'Macedonia', code: 'MK' },
    // { initials: 'MDG', name: 'Madagascar', code: 'MG' },
    // { initials: 'MWI', name: 'Malawi', code: 'MW' },
    // { initials: 'MYS', name: 'Malaysia', code: 'MY' },
    // { initials: 'MDV', name: 'Maldives', code: 'MV' },
    // { initials: 'MLI', name: 'Mali', code: 'ML' },
    // { initials: 'MLT', name: 'Malta', code: 'MT' },
    // { initials: 'MHL', name: 'Marshall Islands', code: 'MH' },
    // { initials: 'MRT', name: 'Mauritania', code: 'MR' },
    // { initials: 'MUS', name: 'Mauritius', code: 'MU' },
    // { initials: 'MEX', name: 'Mexico', code: 'MX' },
    // { initials: 'FSM', name: 'Micronesia', code: 'FM' },
    // { initials: 'MDA', name: 'Moldova', code: 'MD' },
    // { initials: 'MCO', name: 'Monaco', code: 'MC' },
    // { initials: 'MNG', name: 'Mongolia', code: 'MN' },
    // { initials: 'MNE', name: 'Montenegro', code: 'ME' },
    // { initials: 'MAR', name: 'Morocco', code: 'MA' },
    // { initials: 'MOZ', name: 'Mozambique', code: 'MZ' },
    // { initials: 'MMR', name: 'Myanmar [Burma]', code: 'MM' },
    // { initials: 'NAM', name: 'Namibia', code: 'NA' },
    // { initials: 'NRU', name: 'Nauru', code: 'NR' },
    // { initials: 'NPL', name: 'Nepal', code: 'NP' },
    // { initials: 'NLD', name: 'Netherlands', code: 'NL' },
    // { initials: 'NZL', name: 'New Zealand', code: 'NZ' },
    // { initials: 'NIC', name: 'Nicaragua', code: 'NI' },
    // { initials: 'NER', name: 'Niger', code: 'NE' },
    // { initials: 'NGA', name: 'Nigeria', code: 'NG' },
    // { initials: 'PRK', name: 'North Korea', code: 'KP' },
    // { initials: 'NOR', name: 'Norway', code: 'NO' },
    // { initials: 'OMN', name: 'Oman', code: 'OM' },
    // { initials: 'PAK', name: 'Pakistan', code: 'PK' },
    // { initials: 'PLW', name: 'Palau', code: 'PW' },
    // { initials: 'PAN', name: 'Panama', code: 'PA' },
    // { initials: 'PNG', name: 'Papua New Guinea', code: 'PG' },
    // { initials: 'PRY', name: 'Paraguay', code: 'PY' },
    // { initials: 'PER', name: 'Peru', code: 'PE' },
    // { initials: 'PHL', name: 'Philippines', code: 'PH' },
    // { initials: 'POL', name: 'Poland', code: 'PL' },
    { initials: 'PRT', name: 'Portugal', code: 'PT' },
    // { initials: 'QAT', name: 'Qatar', code: 'QA' },
    // { initials: 'COG', name: 'Republic of the Congo', code: 'CG' },
    // { initials: 'ROU', name: 'Romania', code: 'RO' },
    // { initials: 'RUS', name: 'Russia', code: 'RU' },
    // { initials: 'RWA', name: 'Rwanda', code: 'RW' },
    // { initials: 'KNA', name: 'Saint Kitts and Nevis', code: 'KN' },
    // { initials: 'LCA', name: 'Saint Lucia', code: 'LC' },
    // { initials: 'VCT', name: 'Saint Vincent and the Grenadines', code: 'VC' },
    // { initials: 'WSM', name: 'Samoa', code: 'WS' },
    // { initials: 'SMR', name: 'San Marino', code: 'SM' },
    // { initials: 'STP', name: 'São Tomé and Príncipe', code: 'ST' },
    { initials: 'SAU', name: 'Saudi Arabia', code: 'SA' },
    // { initials: 'SEN', name: 'Senegal', code: 'SN' },
    { initials: 'SRB', name: 'Serbia', code: 'RS' },
    // { initials: 'SYC', name: 'Seychelles', code: 'SC' },
    // { initials: 'SLE', name: 'Sierra Leone', code: 'SL' },
    // { initials: 'SGP', name: 'Singapore', code: 'SG' },
    // { initials: 'SVK', name: 'Slovakia', code: 'SK' },
    // { initials: 'SVN', name: 'Slovenia', code: 'SI' },
    // { initials: 'SLB', name: 'Solomon Islands', code: 'SB' },
    // { initials: 'SOM', name: 'Somalia', code: 'SO' },
    // { initials: 'ZAF', name: 'South Africa', code: 'ZA' },
    // { initials: 'KOR', name: 'South Korea', code: 'KR' },
    // { initials: 'ESP', name: 'Spain', code: 'ES' },
    // { initials: 'LKA', name: 'Sri Lanka', code: 'LK' },
    // { initials: 'SDN', name: 'Sudan', code: 'SD' },
    // { initials: 'SUR', name: 'Suriname', code: 'SR' },
    // { initials: 'SWZ', name: 'Swaziland', code: 'SZ' },
    // { initials: 'SWE', name: 'Sweden', code: 'SE' },
    // { initials: 'CHE', name: 'Switzerland', code: 'CH' },
    // { initials: 'SYR', name: 'Syria', code: 'SY' },
    // { initials: 'TWN', name: 'Taiwan', code: 'TW' },
    // { initials: 'TJK', name: 'Tajikistan', code: 'TJ' },
    // { initials: 'TZA', name: 'Tanzania', code: 'TZ' },
    // { initials: 'THA', name: 'Thailand', code: 'TH' },
    // { initials: 'TGO', name: 'Togo', code: 'TG' },
    // { initials: 'TON', name: 'Tonga', code: 'TO' },
    // { initials: 'TTO', name: 'Trinidad and Tobago', code: 'TT' },
    // { initials: 'TUN', name: 'Tunisia', code: 'TN' },
    // { initials: 'TUR', name: 'Turkey', code: 'TR' },
    { initials: 'TKM', name: 'Turkmenistan', code: 'TM' },
    // { initials: 'TUV', name: 'Tuvalu', code: 'TV' },
    // { initials: 'UGA', name: 'Uganda', code: 'UG' },
    // { initials: 'UKR', name: 'Ukraine', code: 'UA' },
    // { initials: 'ARE', name: 'United Arab Emirates', code: 'AE' },
    // { initials: 'GBR', name: 'United Kingdom', code: 'GB' },
    // { initials: 'USA', name: 'United States', code: 'US' },
    { initials: 'URY', name: 'Uruguay', code: 'UY' },
    // { initials: 'UZB', name: 'Uzbekistan', code: 'UZ' },
    // { initials: 'VUT', name: 'Vanuatu', code: 'VU' },
    // { initials: 'VAT', name: 'Vatican City', code: 'VA' },
    // { initials: 'VEN', name: 'Venezuela', code: 'VE' },
    // { initials: 'VNM', name: 'Vietnam', code: 'VN' },
    // { initials: 'ESH', name: 'Western Sahara', code: 'EH' },
    // { initials: 'YEM', name: 'Yemen', code: 'YE' },
    // { initials: 'ZMB', name: 'Zambia', code: 'ZM' }
]

module.exports = { countries }