const countries = [
    { initials: 'AFG', name: 'Afghanistan', code: 'AF' },
    { initials: 'ATG', name: 'Antigua and Barbuda', code: 'AG' },
    { initials: 'AGO', name: 'Angola', code: 'AO' },
    { initials: 'AUT', name: 'Austria', code: 'AT' },
    { initials: 'BRB', name: 'Barbados', code: 'BB' },
    { initials: 'BFA', name: 'Burkina Faso', code: 'BF' },
    { initials: 'BEN', name: 'Benin', code: 'BJ' },
    { initials: 'BTN', name: 'Bhutan', code: 'BT' },
    { initials: 'BWA', name: 'Botswana', code: 'BW' },
    { initials: 'BLZ', name: 'Belize', code: 'BZ' },
    { initials: 'COD', name: 'Democratic Republic of the Congo', code: 'CD' },
    { initials: 'CAF', name: 'Central African Republic', code: 'CF' },
    { initials: 'COG', name: 'Republic of the Congo', code: 'CG' },
    { initials: 'CIV', name: 'Ivory Coast', code: 'CI' },
    { initials: 'CHL', name: 'Chile', code: 'CL' },
    { initials: 'CMR', name: 'Cameroon', code: 'CM' },
    { initials: 'CHN', name: 'China', code: 'CN' },
    { initials: 'COL', name: 'Colombia', code: 'CO' },
    { initials: 'CZE', name: 'Czech Republic', code: 'CZ' },
    { initials: 'DJI', name: 'Djibouti', code: 'DJ' },
    { initials: 'DZA', name: 'Algeria', code: 'DZ' },
    { initials: 'EGY', name: 'Egypt', code: 'EG' },
    { initials: 'ESP', name: 'Spain', code: 'ES' },
    { initials: 'FRA', name: 'France', code: 'FR' },
    { initials: 'GEO', name: 'Georgia', code: 'GE' },
    { initials: 'GHA', name: 'Ghana', code: 'GH' },
    { initials: 'GMB', name: 'Gambia', code: 'GM' },
    { initials: 'GIN', name: 'Guinea', code: 'GN' },
    { initials: 'GNQ', name: 'Equatorial Guinea', code: 'GQ' },
    { initials: 'GRC', name: 'Greece', code: 'GR' },
    { initials: 'IDN', name: 'Indonesia', code: 'ID' },
    { initials: 'IND', name: 'India', code: 'IN' },
    { initials: 'IRQ', name: 'Iraq', code: 'IQ' },
    { initials: 'ITA', name: 'Italy', code: 'IT' },
    { initials: 'JPN', name: 'Japan', code: 'JP' },
    { initials: 'KEN', name: 'Kenya', code: 'KE' },
    { initials: 'KHM', name: 'Cambodia', code: 'KH' },
    { initials: 'KNA', name: 'Saint Kitts and Nevis', code: 'KN' },
    { initials: 'KOR', name: 'South Korea', code: 'KR' },
    { initials: 'LAO', name: 'Laos', code: 'LA' },
    { initials: 'LBN', name: 'Lebanon', code: 'LB' },
    { initials: 'LSO', name: 'Lesotho', code: 'LS' },
    { initials: 'MAR', name: 'Morocco', code: 'MA' },
    { initials: 'MDG', name: 'Madagascar', code: 'MG' },
    { initials: 'MLI', name: 'Mali', code: 'ML' },
    { initials: 'MRT', name: 'Mauritania', code: 'MR' },
    { initials: 'MLT', name: 'Malta', code: 'MT' },
    { initials: 'MUS', name: 'Mauritius', code: 'MU' },
    { initials: 'MDV', name: 'Maldives', code: 'MV' },
    { initials: 'MWI', name: 'Malawi', code: 'MW' },
    { initials: 'MOZ', name: 'Mozambique', code: 'MZ' },
    { initials: 'NAM', name: 'Namibia', code: 'NA' },
    { initials: 'NLD', name: 'Netherlands', code: 'NL' },
    { initials: 'PAN', name: 'Panama', code: 'PA' },
    { initials: 'PER', name: 'Peru', code: 'PE' },
    { initials: 'PAK', name: 'Pakistan', code: 'PK' },
    { initials: 'PRT', name: 'Portugal', code: 'PT' },
    { initials: 'ROU', name: 'Romania', code: 'RO' },
    { initials: 'SRB', name: 'Serbia', code: 'RS' },
    { initials: 'RUS', name: 'Russia', code: 'RU' },
    { initials: 'RWA', name: 'Rwanda', code: 'RW' },
    { initials: 'SAU', name: 'Saudi Arabia', code: 'SA' },
    { initials: 'SGP', name: 'Singapore', code: 'SG' },
    { initials: 'SVK', name: 'Slovakia', code: 'SK' },
    { initials: 'SLE', name: 'Sierra Leone', code: 'SL' },
    { initials: 'SEN', name: 'Senegal', code: 'SN' },
    { initials: 'SOM', name: 'Somalia', code: 'SO' },
    { initials: 'SUR', name: 'Suriname', code: 'SR' },
    { initials: 'SYR', name: 'Syria', code: 'SY' },
    { initials: 'SWZ', name: 'Swaziland', code: 'SZ' },
    { initials: 'TCD', name: 'Chad', code: 'TD' },
    { initials: 'THA', name: 'Thailand', code: 'TH' },
    { initials: 'TKM', name: 'Turkmenistan', code: 'TM' },
    { initials: 'TUN', name: 'Tunisia', code: 'TN' },
    { initials: 'TUR', name: 'Turkey', code: 'TR' },
    { initials: 'TWN', name: 'Taiwan', code: 'TW' },
    { initials: 'TZA', name: 'Tanzania', code: 'TZ' },
    { initials: 'UKR', name: 'Ukraine', code: 'UA' },
    { initials: 'UGA', name: 'Uganda', code: 'UG' },
    { initials: 'URY', name: 'Uruguay', code: 'UY' },
    { initials: 'VCT', name: 'Saint Vincent and the Grenadines', code: 'VC' },
    { initials: 'VEN', name: 'Venezuela', code: 'VE' },
    { initials: 'VNM', name: 'Vietnam', code: 'VN' },
    { initials: 'YEM', name: 'Yemen', code: 'YE' },
    { initials: 'ZAF', name: 'South Africa', code: 'ZA' },
    { initials: 'ZMB', name: 'Zambia', code: 'ZM' }
]

module.exports = { countries }